Initial copy
cockpit-project/cockpit-machines pull request #1
Opened 2021-03-18 18:43 UTC by KKoukiou

2021-03-18 19:23 UTC, marusak commented
Regarding translations - I've created https://github.com/cockpit-project/cockpit-machines-weblate
We need to though correctly initialize it - with correct .pot and .po files (lets not loose translations) and also lets put there the same README as we have in other repos.
Once we have that, then I'll create also weblate component.

2021-03-21 18:02 UTC, martinpitt commented
This [debian-stable lifecycle test](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-1-20210319-165804-a210cb65-debian-stable/log.html#25-2) looks a bit dubious. Retrying for comparison.

2021-03-22 08:22 UTC, martinpitt requested changes

2021-03-22 08:22 UTC, martinpitt commented on test/browser/main.fmf
> +  - cockpit-podman
-machines

2021-03-22 08:22 UTC, martinpitt commented on test/browser/main.fmf
> +  - libvirt-python3
I'm also quite sure that this will need a few more dependencies, some qemu stuff. We can debug this while fixing packit tests.

2021-03-22 08:22 UTC, martinpitt commented on test/check-machines-consoles
> +        b.wait_in_text("#vm-subVmTest1-state", "Running")  # running or paused
This "autopep8" commit should go away after a re-import after https://github.com/cockpit-project/cockpit/pull/15561 lands

2021-03-22 08:22 UTC, martinpitt commented on test/check-machines-networks
> +    if net_devices_str not in ["\n", "\r\n"]:
Same, fixed in https://github.com/cockpit-project/cockpit/pull/15561

2021-03-22 08:22 UTC, martinpitt commented on test/check-machines-create
> +            r"mkdir -p /var/lib/libvirt/pools/tmp\ pool; chmod a+rwx /var/lib/libvirt/pools/tmp\ pool",
Also done in https://github.com/cockpit-project/cockpit/pull/15561

2021-03-22 08:22 UTC, martinpitt commented on README.md
> +- cockpit-machines communicates to libivrt through its [dbus API](https://libvirt.org/dbus.html).
"ivrt" typo

2021-03-22 08:22 UTC, martinpitt commented on .github/workflows/npm-update.yml
> +  # can be run manually on https://github.com/cockpit-project/cockpit-podman/actions
podman → machines

2021-03-22 08:22 UTC, martinpitt commented on .github/workflows/po-refresh.yml
> +  # can be run manually on https://github.com/cockpit-project/starter-kit/actions
starter-kit → machines

2021-03-22 12:23 UTC, martinpitt approved these changes
Thanks! Let's land this, and fix up the rest in follow-ups.

2021-03-22 12:43 UTC, merged