Show virtual interface's TAP device
cockpit-project/cockpit-machines pull request #1077
Opened 2023-05-15 13:00 UTC by skobyda

Network interfaces that are attached to VMs have a TUN/TAP device. If you want to check manually, e.g. why the device is not working correctly, you need to know the interface name.
Name of the tap device is  be specified with attribute of the <target> element. If no target dev is specified upon vnic attachement, libvirt will create a new standard tap device with a name of the pattern "vnetN" Shot this device in the list of VM's interfaces. In the future, we could also allow user to choose/name a tap device during vNIC attachement.

Fixes #1047

![Screenshot from 2023-05-15 15-00-14](https://github.com/cockpit-project/cockpit-machines/assets/42733240/5afd3a85-5c3f-422b-8163-22532ce115fd)

2023-05-25 13:07 UTC, skobyda commented
Updated pixels

2023-06-21 20:12 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230621-195735-af676aa5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-21 20:12 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230621-195735-af676aa5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-21 22:16 UTC, skobyda commented
Line coverage is related to the code I just moved around, not anything I added in this PR. Tests have only known flakes

2023-06-21 22:16 UTC, skobyda commented
Ready for code review

2023-06-22 05:32 UTC, martinpitt submitted a review, later dismissed
Thank you, LGTM! (Re-running flaked test)

Can you please update the screenshot to be less wide, and update the description for a release note?

2023-06-22 05:32 UTC, martinpitt commented on src/components/vm/nics/vmNicsCard.jsx
> +    const checkDeviceAviability = (network) => {
"Aviability" means checking if the device can fly, right? ✈️

The typo already exists in the moved code, it's just a funny typo.

2023-06-23 10:26 UTC, skobyda commented
Made the IP address column consistent with the source column.
@garrett you wanted to see what it would look like with horizontal and vertical descriptionlist for this. Here some screenshots:

### Horizontal


### Horizontal Fuild


### Vertical
![Screenshot from 2023-06-23 12-22-50](https://github.com/cockpit-project/cockpit-machines/assets/42733240/a18f3f29-396a-4a23-b8b3-4762017ff9ee)
![Screenshot from 2023-06-23 12-17-06](https://github.com/cockpit-project/cockpit-machines/assets/42733240/7c7f002b-da43-428f-b1d2-adbdb1abbc44)
![Screenshot from 2023-06-23 12-23-31](https://github.com/cockpit-project/cockpit-machines/assets/42733240/0b99f0a7-8172-4e71-a5f4-021643bed331)

2023-06-26 08:36 UTC, garrett reviewed
Let's go with "horizontal fluid" for now. We don't use top-labelling much elsewhere in Cockpit.

What happens when you're in mobile? Does it "do the right thing"? If it doesn't, and vertical works, then we'll just go with that instead.

2023-06-26 08:52 UTC, skobyda commented
@garrett Updated the PR to use fluid:

![Screenshot from 2023-06-26 10-51-11](https://github.com/cockpit-project/cockpit-machines/assets/42733240/1fdadbcf-b0e9-4040-8c97-10c7704cdd54)

2023-06-26 09:03 UTC, skobyda commented
@garrett Updated the PR to fluid:
![Screenshot from 2023-06-26 11-03-08](https://github.com/cockpit-project/cockpit-machines/assets/42733240/4bceb765-ea7e-4db0-9fae-cbea8e7ff0ca)

2023-06-26 09:04 UTC, skobyda commented
And this is how it looks with mobile:

![Screenshot from 2023-06-26 11-04-23](https://github.com/cockpit-project/cockpit-machines/assets/42733240/ae2ba6f7-a9ef-467d-a6dc-1d32a2c25b2d)

2023-06-26 09:19 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 09:19 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 09:19 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                            <Dropdown onSelect={() => this.setState({ isDropdownOpen: false })}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 09:19 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                                toggle={<KebabToggle onToggle={(_event, isDropdownOpen) => this.setState({ isDropdownOpen })} />}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 09:50 UTC, skobyda commented
Dropdown doesn't work correctly, that needs fix

2023-06-26 09:50 UTC, garrett approved these changes
Thanks! Looks good.

2023-06-26 09:54 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-093958-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 09:54 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                                toggle={<KebabToggle onToggle={(_event, isDropdownOpen) => this.setState({ isDropdownOpen })} />}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-093958-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 11:25 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-110643-d19134c5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 11:25 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-110643-d19134c5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 12:43 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-122651-4536b036-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 12:43 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-122651-4536b036-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 13:30 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-124802-255e145d-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 14:13 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-135722-bc6440ae-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 14:13 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-135722-bc6440ae-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 14:13 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                                </DescriptionListGroup>}
These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-135722-bc6440ae-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 15:45 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-152120-afec49af-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 15:45 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-152120-afec49af-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 15:45 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                                </DescriptionListGroup>}
These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-152120-afec49af-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 19:25 UTC, martinpitt commented
@skobyda : It's now conflicty as #1069 also changed pixels, sorry.

2023-06-26 19:28 UTC, martinpitt requested changes
Otherwise LGTM, just needs deconflicting pixels. Thanks!

2023-06-26 19:53 UTC, martinpitt approved these changes
Dakujem!

2023-06-26 20:01 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-194339-36f91e04-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 20:01 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +        </DescriptionListGroup>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-194339-36f91e04-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 20:01 UTC, cockpituous commented on src/components/vm/nics/vmNicsCard.jsx
> +                                </DescriptionListGroup>}
These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-194339-36f91e04-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-26 20:27 UTC, skobyda commented
All green, apart from one unrelated flake

2023-06-26 20:27 UTC, merged