test: add some general checks when deleting storage pools
cockpit-project/cockpit-machines pull request #1146
Opened 2023-07-11 08:02 UTC by yunmingyang

2023-07-11 13:11 UTC, skobyda requested changes

2023-07-11 13:11 UTC, skobyda commented on test/check-machines-storage-pools
> +        b.click(".pf-v5-c-backdrop footer button[aria-disabled=false]:contains(Delete)")
This is failing our test farm at https://artifacts.dev.testing-farm.io/85d99f8d-87ee-4d18-89af-2ee7fc1261e7/

2023-07-11 13:12 UTC, skobyda commented on test/check-machines-storage-pools
> +        b.click(".pf-v5-c-backdrop footer button[aria-disabled=false]:contains(Delete)")
But that should be some flake, because I don't see how this would be failing our tests

2023-07-27 17:10 UTC, yunmingyang commented
Let's try the new selector, and wait the job results

2023-09-04 10:46 UTC, skobyda approved these changes

2023-09-04 10:46 UTC, merged