test: Attach VM's XML and logs to a failed test
cockpit-project/cockpit-machines pull request #1158
Opened 2023-07-24 12:34 UTC by skobyda

2023-07-30 10:35 UTC, martinpitt commented
Fails everywhere:

    # test/machineslib.py:18:1: I001 [*] Import block is un-sorted or un-formatted

2023-07-30 18:33 UTC, martinpitt requested changes
Thanks! This is a nice idea!

2023-07-30 18:33 UTC, martinpitt commented on test/machineslib.py
> +        vms_xml = f"/var/lib/cockpittest/pkg_specific_artifacts/{vm}.xml"
DRY, please use that variable in the m.execute() call.

2023-07-30 18:33 UTC, martinpitt commented on test/machineslib.py
> +        attach(vms_xml, move=False)
Hmm, the first argument is supposed to be a file name, in the local test dir; vms_xml is the file name in the VM. How does that even work like that? You *first* need to m.download() the file and *then* attach it surely?

2023-07-30 18:33 UTC, martinpitt commented on test/machineslib.py
> +            m.download(vms_log, dest)
Dito, this looks the wong way around. Also for repeating the vms_log path.

2023-07-30 18:33 UTC, martinpitt commented on test/machineslib.py
> +        self.downloadVmsArtifacts()
Please only do this on failure, otherwise this wastes too much storage space, and also test time.

2023-07-31 09:28 UTC, skobyda commented
Hmmm that's weird, locally I don't get the error  `test/machineslib.py:18:1: I001 [*] Import block is un-sorted or un-formatted`, even when running `test/static-code` manually

2023-07-31 09:37 UTC, martinpitt commented
@skobyda ruff is installed in our cockpit/tasks container now, see https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#setting-up-development-container

2023-07-31 14:20 UTC, martinpitt approved these changes
Nice, thanks! Do you have a failure somewhere to prove that it works?

2023-07-31 14:21 UTC, martinpitt commented
[This run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1158-20230731-093210-86f4fc47-fedora-38-pybridge/log.html#64) has a flake, and the [result dir](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1158-20230731-093210-86f4fc47-fedora-38-pybridge/index.html) at least has the XML (no log, though)

2023-07-31 14:26 UTC, martinpitt commented
Also no log [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1158-20230731-093210-86f4fc47-ubuntu-stable/index.html)

2023-07-31 14:27 UTC, martinpitt requested changes

2023-07-31 14:27 UTC, martinpitt commented on test/machineslib.py
> +        if m.execute(f"!test -f {vms_log} || echo exists") == "exists":
[This](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1158-20230731-093210-86f4fc47-fedora-38-pybridge/log.html#64) shows why:

   bash: line 1: !test: command not found

/me buys a space

2023-08-03 08:40 UTC, martinpitt approved these changes
Eeeeexcellent, thanks!

2023-08-03 09:24 UTC, merged