Edit vNIC MAC address
cockpit-project/cockpit-machines pull request #116
Opened 2021-04-20 11:40 UTC by skobyda

![Screenshot from 2021-04-20 13-40-19](https://user-images.githubusercontent.com/42733240/115389931-fa0e0800-a1dd-11eb-8027-1fa024290fca.png)

2021-04-20 13:37 UTC, KKoukiou requested changes

2021-04-20 13:37 UTC, KKoukiou commented on cockpit-machines.spec.in
> +%license LICENSE dist/LICENSE
Unrelated change.

2021-04-20 13:37 UTC, KKoukiou commented on src/components/vm/nics/nicEdit.jsx
> +        <FormGroup fieldId="mac" label={_("MAC address")} hasNoPaddingTop>
The fieldId needs to be the same with the id in the nested component for accessibility purposed.

2021-04-20 13:37 UTC, KKoukiou commented on src/libvirt-dbus.js
> +                    console.log("This Happend");
You forgot this :)

2021-04-20 13:37 UTC, KKoukiou commented on src/libvirt-dbus.js
> +        console.log("Thus Happend");
You forgot this.

2021-04-20 13:37 UTC, KKoukiou commented on src/libvirt-dbus.js
> +                    return attachIface({ connectionName, vmId: objPath, mac: newMacAddress, permanent: persistent, hotplug, sourceType: networkType, source: networkSource, model: networkModel });
Could you make the line collapse, it's too long, in my desktop screen it get's hidden :/

2021-04-21 16:22 UTC, KKoukiou approved these changes
Thanks for this feature. I just noriced one more problem, but I am happy if we solve it in a followup, I will leave it up to you:
* When the user edits the mac when the VM is running there is a UI glitch causing both interfaces to appear in the UI for a second or two
* Then if the user will try to edit again the MAC there will be an error.
![Screen Shot 2021-04-22 at 18 22 06](https://user-images.githubusercontent.com/14921356/115587912-7e3fb880-a2ce-11eb-9764-74e76fc6e6da.png)

2021-04-22 11:20 UTC, KKoukiou commented
One failure in the last run that looks suspicious, let's retry: https://logs.cockpit-project.org/logs/pull-116-20210422-071806-fe74b4fa-rhel-9-0/log.html#48

2021-04-22 12:03 UTC, KKoukiou commented
@skobyda can you please add a release note text for this?

2021-04-22 12:03 UTC, merged

2021-04-22 12:34 UTC, skobyda commented
> @skobyda can you please add a release note text for this?

Done https://github.com/cockpit-project/cockpit-machines/pull/116#issue-619249868

2021-04-23 04:20 UTC, martinpitt commented
@KKoukiou Your suspicion was right. Unfortunately we don't re-run these tests 3 times yet. I filed #127 about it, as it now blocks all c-machines PRs.

2021-04-23 06:29 UTC, KKoukiou commented
> @KKoukiou Your suspicion was right. Unfortunately we don't re-run these tests 3 times yet. I filed #127 about it, as it now blocks all c-machines PRs.

Sad :( Will take a look and also for running these tests 3 times in your pR.

2021-04-23 13:09 UTC, lzap commented
Thank you so much! This looks great.