test: Use wait_text to check an empty string
cockpit-project/cockpit-machines pull request #1195
Opened 2023-09-04 10:12 UTC by skobyda

Using wait_in_text(selector, "") always validates as true (since empty string is always subset of any string), rendering the test useless.

2023-09-04 11:23 UTC, martinpitt commented
> wait_js_cond(ph_text_is("#pool-myPoolTwo-system-volume-VolumeOne-usedby","")): Uncaught (in promise) Error: actual text: subVmTest1

... and it fails

2023-09-04 12:00 UTC, skobyda commented
> > wait_js_cond(ph_text_is("#pool-myPoolTwo-system-volume-VolumeOne-usedby","")): Uncaught (in promise) Error: actual text: subVmTest1
> 
> ... and it fails

So the test was really useless

2023-09-05 11:58 UTC, martinpitt requested changes
Thanks for fixing the test properly!

2023-09-05 11:58 UTC, martinpitt commented on test/machineslib.py
> +    def deleteDisk(self, target, vm_name="subVmTest1"):
You just defined this function without using this anywhere. Forgot to commit something?

2023-09-06 07:40 UTC, martinpitt approved these changes
Thanks!

2023-09-06 07:40 UTC, merged