fix: Missing spacing between input and form helper text solves #1164
cockpit-project/cockpit-machines pull request #1354
Opened 2023-12-16 21:22 UTC by ashutosh7i

Hello @jelly & @KKoukiou , i have worked on this issue,
### Image with issue-
![Screenshot from 2023-12-17 01-55-22](https://github.com/cockpit-project/cockpit-machines/assets/44861896/dc9560d0-c7fd-45f1-9371-9e010daa5d62)

After my Solution to the issue-
![image](https://github.com/cockpit-project/cockpit-machines/assets/44861896/a413e074-2b41-4757-87b9-160ac5a36241)

### The fix i implemented is that i replaced  
```
<FormHelper ... /> component
```
with the official component-
```
<HelperText>
                    <HelperTextItem variant="error">{ ... } </HelperTextItem>
</HelperText>
```

![image](https://github.com/cockpit-project/cockpit-machines/assets/44861896/8183550a-fb7f-4a35-b9d2-5599709cf672)

### And tweaked css in Machines.scss
![image](https://github.com/cockpit-project/cockpit-machines/assets/44861896/d38bc622-060f-487b-b2a7-989309ea191e)

this workaround fixed the issue of missing spacing between input and helper text solving #1164

2024-01-16 08:58 UTC, garrett requested changes
This is an improvement, but why are the spaces different?

"Name should not be empty" has 13 pixels of space between the form and the string.

While the rest have 8 px.

PatternFly has 10px.

It seems your fonts are larger though (not the default), so the references above don't matter when comparing to PatternFly (which also doesn't use px to set these values, of course), so I don't know which is correct here, but I do know that they're inconsistent.

So I've checked locally on my machine and it seems the first one here is 10px and the rest are 6px. The first is correct; the rest still are not correct.

![image](https://github.com/cockpit-project/cockpit-machines/assets/10246/749510f1-8018-42f2-8f98-54c480ba89a4)

2024-01-16 09:01 UTC, garrett commented
For reference:

Here's a screenshot of JSX React on PatternFly's demo page @ https://www.patternfly.org/components/helper-text/react-demos

![image](https://github.com/cockpit-project/cockpit-machines/assets/10246/5ee5bdff-fd7c-446d-992a-22e516f6ad7c)

2024-02-01 18:17 UTC, ashutosh7i commented
sure @garrett i am onto it.

2025-09-03 07:03 UTC, mvollmer commented
This is still broken after the update to PF6:

<img width="853" height="728" alt="image" src="https://github.com/user-attachments/assets/7c036312-dbce-4f4a-91c0-f0e27d2d8dda" />

2025-09-03 07:11 UTC, mvollmer commented
Patternfly says we should wrap `HelperText` with `FormHelperText` inside a `FormGroup` (which is what our `FormHelper` does), so we need to find a different solution.

I have put this into our backlog: https://issues.redhat.com/browse/COCKPIT-1312

2025-09-03 07:11 UTC, closed without merging