snapshots: Allow disk-only snapshots of running machines
cockpit-project/cockpit-machines pull request #1560
Opened 2024-04-16 11:19 UTC by mvollmer

2024-04-16 11:29 UTC, mvollmer commented
I wasn't able to revert to a disk-only snapshot:

![image](https://github.com/cockpit-project/cockpit-machines/assets/3228183/90b42e68-4b8d-4db2-baf0-6d28fa11a4a1)

Probably tracked by https://issues.redhat.com/browse/RHEL-21549 and fixed by https://www.mail-archive.com/devel@lists.libvirt.org/msg01703.html, but not yet in rhel-9-4.

Should this feature here go to rhel-9-4 or be put on hold until rhel-9-5?

2024-04-16 11:35 UTC, mvollmer commented
> Should this feature here go to rhel-9-4 or be put on hold until rhel-9-5?

Alright, current "main" goes to rhel-9-5 already, this is good to go.

2024-04-16 11:40 UTC, mvollmer commented
I should've used the term "disk-only" instead of "partial" in the code, but I figured out too late that that's what libvirt calls them.

2024-04-16 11:48 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        </FormGroup>
These 32 added lines are not executed by any test.

2024-04-16 11:48 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        if (isExternal && vm.state === "running" && !isPartial && !memoryPath)
This added line is not executed by any test.

2024-04-16 11:48 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                {isExternal && vm.state === 'running' && !isPartial &&
These 2 added lines are not executed by any test.

2024-04-16 11:53 UTC, mvollmer commented
> I should've used the term "disk-only" instead of "partial" in the code, but I figured out too late that that's what libvirt calls them.

Fixed.

2024-04-16 12:07 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        </FormGroup>
These 32 added lines are not executed by any test.

2024-04-16 12:07 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        if (isExternal && vm.state === "running" && !isDiskOnly && !memoryPath)
This added line is not executed by any test.

2024-04-16 12:07 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                {isExternal && vm.state === 'running' && !isDiskOnly &&
These 2 added lines are not executed by any test.

2024-04-16 14:01 UTC, mvollmer commented
This is blocked on https://issues.redhat.com/browse/RHEL-21549

Cockpit should only offer the creation of disk-only external snapshots when they can also be restored. We might have to detect that at run-time, maybe by looking at the libvirt version.

2024-04-23 13:00 UTC, martinpitt commented
For the record: I will never approve this, this is a dangerous and crazy practice to offer and train admins to do. I won't make a fuss if someone else approves, but I refuse any responsibility for this, sorry.

2024-04-23 13:08 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +    );
These 32 added lines are not executed by any test.

2024-04-23 13:30 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +    );
These 32 added lines are not executed by any test.

2024-04-23 13:30 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
>              validationError.memory = _("Memory file can not be empty");
This added line is not executed by any test.

2024-04-23 13:30 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
>              </Form>
These 2 added lines are not executed by any test.

2024-04-26 11:33 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        </FormGroup>
These 32 added lines are not executed by any test.

2024-04-26 11:33 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        if (isExternal && vm.state === "running" && !isDiskOnly && !memoryPath)
This added line is not executed by any test.

2024-04-26 11:33 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                memoryPath: isExternal && vm.state === "running" && !isDiskOnly && memoryPath,
This added line is not executed by any test.

2024-04-26 11:33 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                {isExternal && vm.state === 'running' && !isDiskOnly &&
These 2 added lines are not executed by any test.

2024-04-26 11:33 UTC, cockpituous commented on src/libvirt-xml-create.js
> +        snapElem.appendChild(memoryElem);
These 5 added lines are not executed by any test.

2024-04-26 11:33 UTC, cockpituous commented on src/libvirtApi/snapshot.js
> +        throw new Error("Cowardly refusing to make a disk-only snapshot of a running machine");
This added line is not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        </FormGroup>
These 32 added lines are not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        if (isExternal && vm.state === "running" && !isDiskOnly && !memoryPath)
This added line is not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                memoryPath: isExternal && vm.state === "running" && !isDiskOnly && memoryPath,
This added line is not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                {isExternal && vm.state === 'running' && !isDiskOnly &&
These 2 added lines are not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/libvirt-xml-parse.js
> +            return true;
This added line is not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/libvirtApi/snapshot.js
> +    let flags = (!isExternal || memoryPath) ? 0 : Enum.VIR_DOMAIN_SNAPSHOT_CREATE_DISK_ONLY;
This added line is not executed by any test.

2024-04-26 13:03 UTC, cockpituous commented on src/libvirtApi/snapshot.js
> +        flags |= Enum.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE;
These 2 added lines are not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        </FormGroup>
These 32 added lines are not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +        if (isExternal && vm.state === "running" && !isDiskOnly && !memoryPath)
This added line is not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                memoryPath: isExternal && vm.state === "running" && !isDiskOnly && memoryPath,
This added line is not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                {isExternal && vm.state === 'running' && !isDiskOnly &&
These 2 added lines are not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/libvirt-xml-parse.js
> +            return true;
This added line is not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/libvirtApi/snapshot.js
> +    let flags = (!isExternal || memoryPath) ? 0 : Enum.VIR_DOMAIN_SNAPSHOT_CREATE_DISK_ONLY;
This added line is not executed by any test.

2024-04-26 13:38 UTC, cockpituous commented on src/libvirtApi/snapshot.js
> +        flags |= Enum.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE;
These 2 added lines are not executed by any test.

2024-05-02 12:13 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                           <button onClick={e => e.preventDefault()} className="pf-v5-c-form__group-label-help">
This added line is not executed by any test.

2024-05-02 12:13 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                       onChange={() => onValueChanged("isDiskOnly", false)}
This added line is not executed by any test.

2024-05-02 12:13 UTC, cockpituous commented on src/libvirt-xml-parse.js
> +            return true;
This added line is not executed by any test.

2024-05-02 12:13 UTC, cockpituous commented on src/libvirtApi/snapshot.js
> +        flags |= Enum.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE;
This added line is not executed by any test.

2024-05-03 09:45 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                           <button onClick={e => e.preventDefault()} className="pf-v5-c-form__group-label-help">
This added line is not executed by any test.

2024-05-03 09:45 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                       onChange={() => onValueChanged("isDiskOnly", false)}
This added line is not executed by any test.

2024-05-03 09:45 UTC, cockpituous commented on src/libvirtApi/domain.js
> +    return null;
This added line is not executed by any test.

2024-05-13 10:18 UTC, mvollmer commented
> I wasn't able to revert to a disk-only snapshot:

Hmm, reverting disk-only snapshots might not be that important. Maybe they are only used as a mechanism to get a stable view of disks for the purposes of backup. If that is the case, I would argue that Cockpit doesn't need to offer disk-only snapshots. Completing the backup requires a deep understanding of how external snapshots are implemented and this is best done on the command line or from a program.

2024-05-13 10:29 UTC, mvollmer commented
> Completing the backup requires a deep understanding of how external snapshots are implemented and this is best done on the command line or from a program.

What Cockpit could do is to expose the snapshotted disks as NBD devices so that people can then copy them to their backups.

2024-05-15 08:50 UTC, garrett requested changes
I think this is very dangerous, both for stateful live snapshots (with state and memory) and disk-only, as it breaks expectations, which means it'll break someone's backups, which means someone using Cockpit will eventually lose their data.

We need to talk about snapshots holistically (the complete picture, including internal, external disk-only, and external live snapshots and the supportability and purpose of each) and work on designs that might help to mitigate the very real and likely risk for catastrophic data loss due to external snapshots.

2024-05-15 09:15 UTC, mac2net commented
I mentioned on another thread here that I in fact did break a VM fiddling with the snapshots. I received additional instructions and will do another test shortly.
I understand that documentation has been added to the Redhat 9.4 release but I made a suggestion that documentation could be added via the GUI with a popup link that could at a minimum provide a link to documentation on the web,
<img width="876" alt="image" src="https://github.com/cockpit-project/cockpit-machines/assets/7514835/f55ac984-7660-40da-b282-6a8ca588a9b8">

2024-05-16 12:16 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                           <button onClick={e => e.preventDefault()} className="pf-v5-c-form__group-label-help">
This added line is not executed by any test.

2024-05-16 12:16 UTC, cockpituous commented on src/components/vm/snapshots/vmSnapshotsCreateModal.jsx
> +                       onChange={() => onValueChanged("isDiskOnly", false)}
This added line is not executed by any test.

2024-05-16 12:16 UTC, cockpituous commented on src/libvirtApi/domain.js
> +    return null;
This added line is not executed by any test.

2024-05-29 14:48 UTC, mvollmer commented
This is dead for now. No disk-only snapshots of running VMs in Cockpit, see https://issues.redhat.com/browse/COCKPIT-1112

2024-05-29 14:48 UTC, closed without merging