create-vm-dialog:  Don't use default nodeMaxMemory
cockpit-project/cockpit-machines pull request #211
Opened 2021-06-21 14:28 UTC by KKoukiou

2021-06-22 10:20 UTC, skobyda requested changes
I believe this introduces a bug which I fixed some time ago with Math.Floor(). The reason why there was a Math.Floor, which rounds number **down**, was that the number of available memory is never larger by a rounding error.

Imagine you have 15.4603516GiB of free space. The `toReadableNumber()` would round it **up** to 15.5GiB. If then user actually inputs 15.5GiB, they would assign more memory than is actually available.

2021-06-22 10:23 UTC, KKoukiou commented
> I believe this introduces a bug which I fixed some time ago with Math.Floor(). The reason why there was a Math.Floor, which rounds number **down**, was that the number of available memory is never larger by a rounding error.
> 
> Imagine you have 15.4603516GiB of free space. The `toReadableNumber()` would round it **up** to 15.5GiB. If then user actually inputs 15.5GiB, they would assign more memory than is actually available.

toReadableNumber will not round it but trim everything after 4. So it will be 15.4.

2021-06-22 10:29 UTC, skobyda commented
> toReadableNumber will not round it but trim everything after 4. So it will be 15.4.

Are you sure? I just copied the function to nodeJs, tried to run it with `toReadableNumber(15.4603546)` and it returned string "15.5".

2021-06-22 10:31 UTC, skobyda commented
> > I believe this introduces a bug which I fixed some time ago with Math.Floor(). The reason why there was a Math.Floor, which rounds number **down**, was that the number of available memory is never larger by a rounding error.
> > Imagine you have 15.4603516GiB of free space. The `toReadableNumber()` would round it **up** to 15.5GiB. If then user actually inputs 15.5GiB, they would assign more memory than is actually available.
> 
> toReadableNumber will not round it but trim everything after 4. So it will be 15.4.

The function is basically just a wrapper for .toFixed(), which seems to round numbers up/down. You can try by running: 15.4603516.toFixed(1), it will round it up to 15.5

2021-06-22 12:18 UTC, skobyda requested changes

2021-06-22 12:18 UTC, skobyda commented on src/helpers.js
> +        const fixed1 = Math.floor((number * 10 ) / 10);
Breaks make check:

```suggestion
        const fixed1 = Math.floor((number * 10) / 10);
```

2021-06-22 12:21 UTC, KKoukiou commented on src/helpers.js
> +        const fixed1 = Math.floor((number * 10 ) / 10);
Oops

2021-06-22 16:01 UTC, skobyda commented on src/helpers.js
>          return (number - fixed1 === 0) ? number.toFixed(0) : fixed1;
I believe this has to be also adjusted?
```suggestion
        return (number - fixed1 === 0) ? Math.floor(number) : fixed1;
```

2021-06-23 09:08 UTC, skobyda approved these changes
Thanks, LGTM

2021-06-23 09:11 UTC, merged