Disable non-shared storage migration for some distros
cockpit-project/cockpit-machines pull request #272
Opened 2021-07-23 16:11 UTC by skobyda

When copy-storage option is disabled, storage row is hidden and shared-storage is assumed. This is not perfect, as user might not realize they need to have shared storage set up, so perhaps some warning or change of design could be done.

![Screenshot from 2021-07-23 18-10-21](https://user-images.githubusercontent.com/42733240/126810890-b744e951-9651-444b-860b-6ff856200769.png)

Fixes #247

2021-07-26 14:37 UTC, garrett approved these changes
For a simple removal of live migration copying, this works, provided the help text is still accurate (and I think it is).

UI approved; someone else should review the React. :wink:

2021-07-26 16:03 UTC, KKoukiou commented
> For a simple removal of live migration copying, this works, provided the help text is still accurate (and I think it is).
> 
> UI approved; someone else should review the React. wink

I don't think there is a help text at this point. We need to add in the modal modal description a hint that the storage is supposed to be shared.

2021-07-26 16:06 UTC, KKoukiou requested changes
@garrett can you please suggest a text to be added in the modal description that suggest that the storage can only be shared? (applicable for RHEL)

2021-07-27 14:43 UTC, garrett commented
Sorry; I didn't understand what was needed. Thanks for pointing it out.

What about this?

"Storage volumes must be shared between this host and the destination host."

![machines-migrate-dialog](https://user-images.githubusercontent.com/10246/127174520-13972b5a-8372-4c75-af8b-9dcfce0fa4a9.png)

2021-07-28 15:45 UTC, KKoukiou commented
@skobyda friendly ping for update :)

2021-07-28 23:28 UTC, skobyda commented
Updated:

![Screenshot from 2021-07-29 01-27-22](https://user-images.githubusercontent.com/42733240/127409034-d70d0ece-7375-4181-8552-a6c819858246.png)

2021-07-29 06:27 UTC, KKoukiou approved these changes

2021-07-29 06:28 UTC, KKoukiou commented
/packit test

2021-07-29 07:45 UTC, merged