Replace adding/removing vNICs API's with virt-xml
cockpit-project/cockpit-machines pull request #356
Opened 2021-09-06 23:21 UTC by skobyda

I'm just trying out the waters with the pull request to see that we agree with the approach used for using virt-xml.
Once we agree on a correct approach, APIs for adding/removing disks, filesystems, memory-blocking can be replaced with virt-xml too.

2021-09-07 07:47 UTC, KKoukiou requested changes

2021-09-07 07:47 UTC, KKoukiou commented on src/libvirtApi/domain.js
> +        `virt-xml -c qemu:///${connectionName} ${vmName} --add-device --network mac=${mac},type=${sourceType},source=${source},model=${model} ${define} ${update}`,
When 'generate automatically' is chosen for the MAC the mac variable is undefined and clicking add would result in an error:
```  ERROR XML error: unable to parse mac address 'undefined'  ```

2021-09-07 07:48 UTC, KKoukiou commented
Reg the virt-xml approach I am happy with the change.

2021-09-10 18:54 UTC, KKoukiou commented
@skobyda I updated the PR _ it was just a tiny tweak :)

2021-09-10 20:26 UTC, KKoukiou reviewed
testNICAdd consistently fails on some distros - with:
> warning: ERROR    Error: --network mac=52:54:00:a5:f8:c0,type=direct,source=eth1,model=virtio: The MAC address '52:54:00:a5:f8:c0' is in use by another virtual machine.

2021-09-15 06:40 UTC, skobyda commented
Fixed the failing test and updated pixel reference (the MAC address filled in NIC Add dialog changed)

2021-09-15 07:16 UTC, KKoukiou requested changes
Previously one could choose 'Generate automatically' and the API would be fed with an undefined value for the mac address, resulting in an auto generation of a new / non conflicting mac address. Now this commit - stops testing this functionality of 'Generate automatically'  if I am seeing correctly. 

Is virt-xml not able to auto generate mac addresses?

2021-09-15 07:26 UTC, KKoukiou reviewed
Ok I just realized that autogeneration of macs works still fine - but then why did you set the mac in all the tests now?

2021-09-15 07:37 UTC, KKoukiou reviewed
OK I see now - we had a preset mac address in the dialog class. How about removing it and let the dialog generate for us? (So that we tests that functionality as well)

2021-09-15 07:47 UTC, KKoukiou reviewed
Alright - let's get this in - the tests rely on knowing the mac address for doing the xmllint checks. And we need to add a tests for mac address autogeneration as a followup.

2021-09-15 09:24 UTC, KKoukiou approved these changes

2021-09-15 09:25 UTC, KKoukiou approved these changes

2021-09-15 09:26 UTC, merged