Introduce virt-xml into disk and filesystem's attach/detach APIs
cockpit-project/cockpit-machines pull request #394
Opened 2021-09-24 13:00 UTC by skobyda

2021-09-27 15:14 UTC, KKoukiou commented
Fixed the filesystem, disks still broken: https://logs.cockpit-project.org/logs/pull-394-20210924-130035-1e3d9861-fedora-34/log.html

2021-10-08 11:50 UTC, skobyda commented
This is currently blocked on https://github.com/virt-manager/virt-manager/pull/311

2022-02-14 07:19 UTC, martinpitt commented
The fix landed in upstream virt-manager 26 days ago, but not released yet AFAICS.

2022-04-07 07:19 UTC, skobyda commented
There is already a release in fedora 36 and ubuntu 2204. I can get going with this PR :)

2022-09-07 10:59 UTC, skobyda commented
This now passes on all distros where virt-xml (virt-manager package) is >= 4.0 . I wonder if I should just keep this PR blocked until it's released in the other distros too, or just write an exception/antipattern for it

2022-09-08 06:46 UTC, martinpitt requested changes
I see that using `virt-xml` is probably nicer in the long run, as it's a bit more abstract than directly modifying the XML. But as long as this still breaks on so many supported OSes, I feel that we shouldn't land this -- this would appear as a regression. So either we need to support both code paths for now (ugh!), or just shelve this for a while?

2022-09-08 06:46 UTC, martinpitt commented on src/libvirtApi/domain.js
> +    return cockpit.script(
Please use cockpit.spawn() for this, pass this as a proper array, and avoid the shell.

2022-09-08 06:46 UTC, martinpitt commented on src/libvirt-xml-parse.js
> +                address: { // optional
This commit should not stand on its own. It adds this new field which is not used anywhere, nor does the commit message justify it. I suppose it should be squashed into some future commit that uses it?

2022-09-08 06:46 UTC, martinpitt commented on src/libvirt-xml-parse.js
> +                    type: addressElem ? driverElem.getAttribute('type') : undefined,
Repeating the `addressElem` here is a bit nasty -- how about `address: addresElem ? { bus: ... } : {}`

2023-01-31 11:13 UTC, KKoukiou commented
@skobyda this looks still blocked at least for rhel-8-8, as we still update that, but seems like virt-xml is not updated there.

2023-02-02 12:23 UTC, skobyda commented
> @skobyda this looks still blocked at least for rhel-8-8, as we still update that, but seems like virt-xml is not updated there.

Yeah I updated this PR last week to see where it still continues to fail. I'd not try to push this until every distro gets new version of virt-xml

2023-10-13 06:36 UTC, KKoukiou commented
This is probably unblocked by now?

2023-10-13 10:05 UTC, skobyda commented
> This is probably unblocked by now?

No idea, let's re-trigger

2023-10-13 10:31 UTC, cockpituous commented on src/libvirtApi/domain.js
> +        if (busType === "usb" || busType === "scsi" || busType === "sata") {
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-394-20231013-100800-8c396984-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-13 10:31 UTC, cockpituous commented on src/libvirtApi/domain.js
> +                addressType = "usb";
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-394-20231013-100800-8c396984-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-13 10:38 UTC, skobyda commented
> This is probably unblocked by now?

Nope, old version of virt-xml is still present on centos-8-stream and rhel-8-*, so this PR will not get merged until we stop supporting those distros

2024-05-14 10:14 UTC, mvollmer commented
@martinpitt, @KKoukiou, what's the point of using `virt-xml`? Does it augment the XML with its own knowledge of best defaults? Otherwise this looks like a step back to me, in the JSON > XML > CSV hierachy.  (I think we need to worry about quoting when constructing the virt-xml invocations, for example.)

2024-05-14 10:19 UTC, mvollmer commented
Please reopen if this is still wanted.

2026-05-21 13:16 UTC, closed without merging

2026-05-21 13:16 UTC, mvollmer commented
Obsoleted by #2581.