Show PCI device's slot as one combined string in bootorder dialog
cockpit-project/cockpit-machines pull request #731
Opened 2022-06-01 16:34 UTC by skobyda

Fixes: https://bugzilla.redhat.com/show_bug.cgi

2022-06-01 17:02 UTC, jelly commented
> Fixes: https://bugzilla.redhat.com/show_bug.cgi

Hmm, that's not a real bugzilla bug id url :D

2022-06-03 07:44 UTC, jelly requested changes

2022-06-03 07:44 UTC, jelly commented on test/check-machines-settings
> +        pci_output = m.execute("virsh nodedev-list --cap pci")
There should be a `m = self.machine` under `b = self.browser`

2022-07-02 11:45 UTC, martinpitt approved these changes
Thanks!

2022-07-02 11:46 UTC, merged