Robustify OS name sorting in VM creation dialog
cockpit-project/cockpit-machines pull request #744
Opened 2022-06-23 12:47 UTC by skobyda

Split from https://github.com/cockpit-project/cockpit-machines/pull/704

- OS version now has higher priority in sorting than release date
  (It solves the problem when OS of lower version, e.g. rhel-8.11,
   is released later than OS of higher version, e.g. rhel-9.0)
- If neither os version or release date are present, or both are the
  same, sort by by OS name shown in the UI
  (e.g. centos-8 and centos-8-stream have the same version and release
   date, so the only sensible thing left to do is to sort by their name)

2022-06-23 12:53 UTC, martinpitt approved these changes
Thanks! LGTM when green.

2022-06-23 15:20 UTC, garrett requested changes
This doesn't work as expected.

In a lot of places, numbers descend.

![image](https://user-images.githubusercontent.com/10246/175334265-a16d9537-be9d-4ffa-aadf-7f3dc564f50d.png)
![image](https://user-images.githubusercontent.com/10246/175334591-31384d9a-24da-4325-82bf-9568f9324844.png)

But look at Debian...!

![image](https://user-images.githubusercontent.com/10246/175334313-1ccad067-705c-4539-a8ed-0144add1d892.png)

...Is this because 9 > 1?

Don't we have a version field to sort by using a natural number-based sort?

2022-06-24 10:56 UTC, skobyda commented
Fixed the sort to use natural sorting.

2022-06-27 10:57 UTC, martinpitt submitted a review, later dismissed
Thanks!

2022-06-29 09:18 UTC, garrett approved these changes
Looks great now! Thanks!

2022-06-29 09:33 UTC, martinpitt approved these changes
Thanks!

2022-06-29 11:54 UTC, skobyda commented
fedora-rawhide failed with: `AttributeError: '_DebugOutcome' object has no attribute 'errors'`.
I've seen this error in other PRs, so unrelatede to this one

2022-06-29 11:54 UTC, merged