Show toast notication if VM's storage deletion fails
cockpit-project/cockpit-machines pull request #759
Opened 2022-07-13 09:53 UTC by skobyda

Show toast notication if VM's storage deletion fails

If VM deletion fails user is shown an error message in the VM deletion
dialog. But if VM deletion passes, but subsequent deletion of its
storage fails, there is no error message shown, as the VM along with
its dialog is already deleted and a VM deletion dialog unmounted from
the UI.
Fix this by adding a warning message about unsuccessful storage deletion
to the toast alerts.

2022-07-13 09:53 UTC, skobyda commented
If Vm deletion fails:
![Screenshot from 2022-07-13 10-55-49](https://user-images.githubusercontent.com/42733240/178705858-4cac84b7-27f3-4ae0-829f-5550978badfb.png)

If VM's storage deletion fails:
![Screenshot from 2022-07-13 11-47-43](https://user-images.githubusercontent.com/42733240/178705892-fde066b8-4a16-4e31-9c4f-53b998655bee.png)

2022-07-13 12:10 UTC, garrett commented
What happened with the spacing? The spacing should be like this:

![image](https://user-images.githubusercontent.com/10246/178728995-e43a2232-32b4-44f5-ab2d-f3b1d4a562d6.png)

(More vertical spacing is needed nearly everywhere except between the list and its declaration.)

Here's the difference with an "onion skin" approach (to let you see through to the original):

![image](https://user-images.githubusercontent.com/10246/178729396-e9020574-a304-4091-9487-4e04b9633ea0.png)

The text needs work too.
"Could not delete almalinux8-2022-7-13-G"

Additionally, what can someone do here in this modal to make deletion work? I don't see anything that can be done different. Therefore, it should be a notification after the deletion attempt, not within the modal itself.

2022-07-13 12:12 UTC, garrett commented
Why is this notification so far down the page? It's overlapping the action buttons for the VM list.

![Screenshot from 2022-07-13 11-56-15](https://user-images.githubusercontent.com/42733240/178706501-48bbd319-78c3-4d5b-a961-be04c0564614.png)

Additionally, it should probably say something like "Could not delete storage volume for almalinux8-2022-7-13-G"

2022-07-13 16:44 UTC, martinpitt requested changes
Thank you! This approach is good, just some details to work out. Plus of course the spacing issues from Garrett.

2022-07-15 12:17 UTC, skobyda commented
> Additionally, it should probably say something like "Could not delete storage volume for almalinux8-2022-7-13-G"

Not every disk attached to the VM has to be a storage volume. Sometimes it can be a direct block device, or a file attached directly to the VM. So how about "Could not delete disk for. .." or just "Could not delete storage for..."?
Or do you not mean storage volume not in a virtualization sense, but in a broader sense as volume == `any identifiable unit of data storage`?

> Additionally, what can someone do here in this modal to make deletion work? I don't see anything that can be done different. Therefore, it should be a notification after the deletion attempt, not within the modal itself.

That could also work, but I see it for another PR, as we do this kind of thing all over c-machines, and currently, Toast Alerts in VM are shown only on the main page, not on the VM page, so it would require bigger refactoring.

2022-07-19 05:57 UTC, martinpitt approved these changes
Could be squashed a bit, but it's good enough. Thank you! I just retried a flake.

2022-07-19 05:57 UTC, martinpitt commented on src/components/vm/deleteDialog.jsx
> +                                console.warn(cockpit.format(_("VM $0 failed to get deleted: $1"), vm.name, exc.message));
Please drop the translation of this. The message id is different than the error message below, it's redundant work for translators, and in bug reports we actually want the English messages.

Edit: the following commit fixes that.

2022-07-19 06:18 UTC, merged

2022-07-19 12:11 UTC, skobyda commented
Current screenshot:

Fixed spacing of in-modal error:
![Screenshot from 2022-07-19 14-09-25](https://user-images.githubusercontent.com/42733240/179746921-b6c12d00-d413-4e1e-8efc-d1d9ee9087fd.png)

Warning message if storage deletion fails:
![Screenshot from 2022-07-19 14-08-55](https://user-images.githubusercontent.com/42733240/179746997-af620c03-80d3-439d-b4f1-716f33a35404.png)

As described on IRC, the issue with a spacing for Toast Alerts is unrelated to this PR, as it was already existing on the main branch:
![Screenshot from 2022-07-19 14-08-55](https://user-images.githubusercontent.com/42733240/179747052-6f47af0a-4f40-440a-ab91-ec620f0abc2f.png)
And therefore should be fixed in a different PR.

2022-07-19 12:14 UTC, skobyda commented
FYI The notification is overlapping with actions only if you click on "Show more". If you don't, it's not overlapping with anything: 
![Screenshot from 2022-07-19 14-14-19](https://user-images.githubusercontent.com/42733240/179747762-551e83ca-ecf0-4291-9f08-aecf688cf0bc.png)

2022-07-19 12:17 UTC, garrett commented
We definitely should fix that error so it's not in the modal dialog. Can you work on a follow-up for this? Thanks!

> FYI The notification is overlapping with actions only if you click on "Show more". And "Show more" can have very long text in some cases, so even if we move notification a bit up, it may still end up covering action buttons if you click on "Show more". If you don't click on "show more", it's not overlapping with anything

It's still not in the right place (if it's at the top-right of the page, it should be at the top-right of the page with a little bit of margin, not nudged down this much), but it's less bad in the collapsed state. Thanks for pointing that out!

2022-07-19 12:32 UTC, skobyda commented
> We definitely should fix that error so it's not in the modal dialog. Can you work on a follow-up for this? Thanks!

As I mentioned, we do this all across c-machines, so I created an [issue](https://github.com/cockpit-project/cockpit-machines/issues/763) and plan to fix it in multiple places at once.


> > FYI The notification is overlapping with actions only if you click on "Show more". And "Show more" can have very long text in some cases, so even if we move notification a bit up, it may still end up covering action buttons if you click on "Show more". If you don't click on "show more", it's not overlapping with anything
> 
> It's still not in the right place (if it's at the top-right of the page, it should be at the top-right of the page with a little bit of margin, not nudged down this much), but it's less bad in the collapsed state. Thanks for pointing that out!