test: allow new ubuntu-stable apparmor pattern
cockpit-project/cockpit-machines pull request #835
Opened 2022-10-21 08:52 UTC by jelly

The new violation has class="file" after operation="open".

2022-10-21 09:05 UTC, jelly commented
This is for https://github.com/cockpit-project/bots/pull/3953

```
audit: type=1400 audit(1665763333.088:67): apparmor="DENIED" operation="open" class="file" profile="virt-aa-helper" name="/var/lib/cockpittest/vm_one/mydisk3" pid=9618 co  mm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

2022-10-21 11:02 UTC, skobyda requested changes

2022-10-21 11:02 UTC, skobyda commented on test/machineslib.py
> +        self.allow_journal_messages('.* type=1400 .* apparmor="DENIED" operation="open" * profile="virt-aa-helper" name="%s.*' % self.vm_tmpdir)
Test so far fails: https://cockpit-logs.us-east-1.linodeobjects.com/pull-835-20221021-105036-d3235509-ubuntu-stable-bots-3953/log.html#26

Shouldn't it be?
```suggestion
        self.allow_journal_messages('.* type=1400 .* apparmor="DENIED" operation="open" .* profile="virt-aa-helper" name="%s.*' % self.vm_tmpdir)
```

2022-10-21 12:17 UTC, jelly commented
Ok, ubuntu-stable failed:
```
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1666351774.836:98): apparmor="DENIED" operation="open" profile="virt-aa-helper" name="/var/lib/cockpittest/vm_one/mydisk3" pid=8446 comm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

Regex needs to be fixed.

2022-10-24 07:31 UTC, marusak approved these changes
Thanks!

2022-10-24 07:33 UTC, merged