Attach watchdog device only to offline XML if hotplug fails
cockpit-project/cockpit-machines pull request #986
Opened 2023-03-21 13:49 UTC by skobyda

In some cases, hotplug of watchdog device to a running VM might fail since there are no more available PCI slots. This is normal behaviour and not really a bug on libvirt side.
However, if hotplug fails, instead of just failing altogether, we can at least try to attach the watchdog to an offline VM. Additionally, we should let user know that operation only succeeded for offline VM state, and hotplug failed, since they might have expected a hotplug to succeed.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2173584

# Offer to apply watchdog changes on next boot if hotplug fails

In some cases, adding a watchdog to a running VM might fail. When that happens, the user can choose to apply a watchdog on next boot.

![234253257-d6bc8d91-7b66-4ef7-b9df-79d554f92b0b](https://user-images.githubusercontent.com/42733240/235896020-7e209f2a-4c7d-4140-90ce-8ab184e8da6e.png)

2023-03-21 13:51 UTC, skobyda commented
@KKoukiou @garrett I'm not really sure if I handle correctly the situation, where operation succeeded only partially (i.e. watchdog was edited for offline XML, but not for live XML, so the VM needs to be rebooted).
Here is how it looks:
[Screencast from 2023-03-21 14-44-56.webm](https://user-images.githubusercontent.com/42733240/226626627-38e60ead-0bc0-409d-a39d-0ad3bf4e8b4c.webm)

2023-03-21 13:55 UTC, skobyda commented
This PR of course also needs tests, which I will implement once we agree if the handling of this situation is correct.

2023-03-22 17:17 UTC, garrett commented
I was thinking that we probably want a "needs restart" indicator, like a round label widget thingy, and it would have an [alert popover](https://www.patternfly.org/v4/components/popover/#alert-popover) that shows the reason when clicked. (It could even show the dismissable alert popover by default on the first time that it is triggered on the details page if there's no other indication that a reboot is needed from a modal.)

It could then be used on the details page, probably in the header to the right of the kebab menu _and also_ on the list too. It would be used for anything that requires a reboot to be effective.

It would basically be a configuration "dirty state" indicator.

2023-03-24 13:52 UTC, skobyda commented
> I was thinking that we probably want a "needs restart" indicator, like a round label widget thingy, and it would have an [alert popover](https://www.patternfly.org/v4/components/popover/#alert-popover) that shows the reason when clicked. (It could even show the dismissable alert popover by default on the first time that it is triggered on the details page if there's no other indication that a reboot is needed from a modal.)
> 
> It could then be used on the details page, probably in the header to the right of the kebab menu _and also_ on the list too. It would be used for anything that requires a reboot to be effective.
> 
> It would basically be a configuration "dirty state" indicator.

Something like this?
![Screenshot from 2023-03-24 14-50-17](https://user-images.githubusercontent.com/42733240/227539121-b3404f94-7736-440b-ae50-72d97acb2779.png)

Hmm, but then I'm wondering what to do if there are multiple causes why VM needs reboot. E.g. user changes VCPU parameters, Memory parameters and Watchdog. All of these take effect after reboot.
Shall we just present this information in this popover in one information, e.g. one sentence like "VM needs reboot: VCPU configuration, memory and watchdog changes will take effect after reboot" ?

2023-03-27 07:22 UTC, garrett commented
Kind of. I was thinking more of a "label" widget with the icon text, so you don't have to expand it to know what it is. And it'd go to the left of the other "label" widgets when on the list. (But it's in the place where I was thinking of here.)

2023-03-27 11:30 UTC, skobyda commented
> it'd go to the left of the other "label" widgets when on the list

What other label widgets do you mean?

2023-03-28 10:48 UTC, skobyda commented
@garrett like this? 

![Screenshot from 2023-03-28 12-47-17](https://user-images.githubusercontent.com/42733240/228212716-3dd95c66-2350-4bf3-93bc-9d6b6c72e912.png)

2023-03-29 07:39 UTC, garrett reviewed
Yes, exactly! We should have a follow-up that adds support for this for other things that needs reboot too. And it should be in the list. (I haven't tested this PR locally yet, but it looks like I expected. Thanks!)

2023-03-29 14:15 UTC, garrett commented
OK, mentioned in ~IRC~ Matrix:

The way it could work is that anything that can cause a reboot to be needed before it can take effect would have its message shown in the popover. If there's more than 1, we could add a horizontal divider between the items and make sure the popover is scrollable (basically `overflow: auto`, which I think is the default?) if it gets too tall.

2023-03-29 14:16 UTC, skobyda commented
> I haven't tested this PR locally yet, but it looks like I expected. Thanks!)

The changes are not pushed yet, so don't bother trying to build it locally

2023-04-12 12:55 UTC, skobyda commented
Since https://github.com/cockpit-project/cockpit-machines/pull/998 is merged, I think we can move with this now.

@garrett This is how it looks like with new label "Pending changes":
[Screencast from 2023-04-12 14-53-34.webm](https://user-images.githubusercontent.com/42733240/231463737-d81ce456-d25a-4775-9e16-a99e363456f9.webm)

2023-04-20 16:11 UTC, garrett commented
Oh, that error looks too verbose. It probably doesn't matter, either, does it? It wasn't applied (for whatever reason) and it will be applied on the next cold boot. Should we even show it? It's more of an implementation debug message, right? It's not actionable (except to shut down and start afresh) as far as I can tell?

2023-04-24 12:23 UTC, skobyda commented
Updated the "Apply on next boot" to secondary button:
![Screenshot from 2023-04-24 14-23-33](https://user-images.githubusercontent.com/42733240/233995150-de201f56-d8f1-474c-b8d9-cabb7f74518d.png)

2023-04-24 12:36 UTC, skobyda commented
Blocked on  https://github.com/cockpit-project/cockpit/pull/18699

2023-04-24 14:02 UTC, skobyda commented
Updated it to warning:
![Screenshot from 2023-04-24 14-42-20](https://user-images.githubusercontent.com/42733240/234019983-80ab5b51-5585-43a7-aa0d-39056b56dcf1.png)

2023-04-24 14:51 UTC, garrett commented
It's better as a warning, but it's still a problem.

- It didn't _fail_... It just couldn't do it now. (If it truly _failed_, you wouldn't even be able to add a watchdog in a deferred way.) 
- Headings shouldn't have colons.
- I still think there's a problem with saying it's an error, even if that's the message we're getting back. This might be a case to use an expandable alert.

Someone didn't want to "hotplug" a watchdog; they wanted to add a watchdog, so we generally shouldn't really talk about "hotplug" in the UI if we can avoid it.

PF docs for expandable alerts:
https://www.patternfly.org/v4/components/alert#expandable-alerts

Or, perhaps better just not show the error message that's returned, especially if know the errors it can return, like this:

> **<!> Could not dynamically add watchdog**
> Adding a watchdog will require a reboot to take effect.

2023-04-24 14:51 UTC, garrett commented
Also: Perhaps we should say "Add on next boot"?

2023-04-24 15:32 UTC, skobyda commented
> Or, perhaps better just not show the error message that's returned, especially if know the errors it can return, like this:

We don't know all the errors it can return. This PR fixes a bugzilla for one specific error (not enough PCI slots), but there can be other errors, which would also benefit from having "Apply on next boot" feature. Maybe present somewhere deep in libvirt/qemu, or maybe added to libvirt/qemu in the future releases,.
So I don't think we should limit this feature only to one error message (not enough PCI slots). 
And I think should not try to have our own list of error messages libvirt returns, which fit this feature. As we can't, with every libvirt/qemu release, constantly check and keep track of any new situations, any new errors, to add to our own list. As said before, they can change, they can add new messages, and remove other messages... and that would too much work to constantly keep track of.

And I also don't think we should hide the error message. It may have useful information to the user, so they can then do a workaround or fix something on their system, in order to make watchdog attachment work.
That's the point why I want to let them choose if they want to "Apply on next boot" or "Cancel". So if the error message contains useful information, they can cancel, do some fix/changes/workaround/whatever locally, and then come back and try again to attach to a running VM again.

2023-04-24 15:46 UTC, skobyda commented
> **<!> Could not dynamically add watchdog**
> Adding a watchdog will require a reboot to take effect

So, maybe something like this (where clicking on "View details" would show error message returned from libvirt/qemu as is) :
![Screenshot from 2023-04-24 17-45-38](https://user-images.githubusercontent.com/42733240/234048517-73c3b8e7-4267-4fff-b568-e10330574486.png)

2023-04-25 08:01 UTC, garrett commented
> So, maybe something like this (where clicking on "View details" would show the raw error message returned from libvirt/qemu) :

Yeah, this works! Thanks!

2023-04-25 10:07 UTC, skobyda commented
New update with an inline Alert with an ExpandableSection:

![Screenshot from 2023-04-25 12-06-31](https://user-images.githubusercontent.com/42733240/234244967-7d437926-b3d8-4e95-8d47-50826b70e962.png)

2023-04-25 10:35 UTC, skobyda commented
> Meanwhile, I managed to hit the PCI error locally and saw that both add buttons (including the disabled one) get a spinner for a second when adding. The spinner state should only be added to the button that was clicked on, not both.

Fixed:
[Screencast from 2023-04-25 12-33-41.webm](https://user-images.githubusercontent.com/42733240/234251553-aab47392-a284-441d-991a-75bc60ac87cb.webm)

2023-04-25 10:42 UTC, skobyda commented
Added a period after description:

![Screenshot from 2023-04-25 12-42-03](https://user-images.githubusercontent.com/42733240/234253257-d6bc8d91-7b66-4ef7-b9df-79d554f92b0b.png)

2023-04-25 13:14 UTC, garrett submitted a review, later dismissed
:+1:

2023-04-26 11:25 UTC, skobyda commented
So far tests look good. Design was approved.

@KKoukiou mind giving this code-review?

2023-05-03 10:00 UTC, martinpitt requested changes
Thanks! Code-wise this looks good to me, but I think the test should cover the full user story.

2023-05-03 10:13 UTC, skobyda commented on test/check-machines-settings
> +        if not m.image.startswith("rhel-8-9") and m.image != "centos-8-stream":
Fixed

2023-05-03 10:13 UTC, skobyda commented on test/check-machines-settings
> +            b.wait_visible("#watchdog-tooltip")
Fixed

2023-05-11 05:03 UTC, martinpitt approved these changes
Thanks!

2023-05-11 06:00 UTC, merged